[CI] Do not run locales commands (locale-gen/update-locale) on CI (following CI upgrade and commands failing)

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -88,8 +88,12 @@ yunohost service add $app --description="Personal finance manager" --log="/var/l
 #=================================================
 ynh_script_progression --message="Installing woob..." --weight=1
 
-locale-gen C.UTF-8
-update-locale C.UTF-8
+# The CI will fail on these, even though the locales package is installed.
+if ! [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
+	locale-gen C.UTF-8
+	update-locale C.UTF-8
+fi
+
 ynh_secure_remove --file="${install_dir}/venv"
 ynh_exec_as $app virtualenv --python=python3 --system-site-packages "${install_dir}/venv"
 (
